<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Global -->
    <xacro:arg name="robot_name" default="f1tenth"/>
    <xacro:property name="robot_name" value="$(arg robot_name)" />
    <xacro:arg name="add_camera" default="false"/>
    <xacro:property name="add_camera" value="$(arg add_camera)" />
    <xacro:arg name="add_aruco" default="false"/>
    <xacro:property name="add_aruco" value="$(arg add_aruco)" />
    <!-- <xacro:property name="params_path" value="$(arg params_path)"/> -->

    <!-- Wheels -->
    <xacro:property name="wheel_diameter" value="0.11" />
    <xacro:property name="wheel_width" value="0.0445" />

    <!-- Chassis -->
    <xacro:property name="chassis_width" value="0.18" />
    <xacro:property name="chassis_length" value="0.1" />
    <xacro:property name="chassis_height" value="0.09" />

    <!-- Joint placement -->
    <xacro:property name="chassis_to_wheel_x" value="${0.31 /2}" />
    <xacro:property name="chassis_to_wheel_y" value="${0.005+ (wheel_width /2) + (chassis_width /2)}" />
    <xacro:property name="chassis_to_wheel_z" value="${wheel_diameter /2}" />

</robot>